spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.111/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.example.LoggerTest: debug

wechat:
  mpAppId: wx1cedbacc589c1ac6
  mpAppSecret: f6c3d805977f08cb2289dace5b816491
  mchId: 3q3243
  mchKey: 2345345
  keyPath: /D #证书路径
  notifyUrl: http://www.baidu.com