spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    passwork: 123456
    url: jdbc:mysql://192.168.201.242/sell?characterEncoding=utf-8&useSSL=false
  jpa:
  show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.example.LoggerTest: debug